import { AppConfig, EntityConfig } from "../shared/types";

// ============================================================
// Code Generator Service — Generates a full Next.js + Prisma
// codebase from a JSON AppConfig.
// ============================================================

export type VirtualFileSystem = Map<string, string>;

export function generateCodebase(config: AppConfig): VirtualFileSystem {
  const vfs = new Map<string, string>();

  // 1. Configs
  vfs.set("package.json", generatePackageJson(config));
  vfs.set("tsconfig.json", generateTsConfig());
  vfs.set("tailwind.config.ts", generateTailwindConfig());
  vfs.set("postcss.config.js", generatePostcssConfig());
  vfs.set("next.config.js", generateNextConfig());

  // 2. Database
  vfs.set("prisma/schema.prisma", generatePrismaSchema(config));
  vfs.set("src/lib/prisma.ts", generatePrismaClient());

  // 3. App Core
  vfs.set("src/app/globals.css", generateGlobalsCss());
  vfs.set("src/app/layout.tsx", generateRootLayout(config));
  vfs.set("src/app/page.tsx", generateHomePage(config));
    vfs.set("src/components/PwaRegister.tsx", generatePwaRegister());

    // 3b. PWA assets
    vfs.set("src/app/manifest.ts", generateManifest(config));
    vfs.set("public/sw.js", generateServiceWorker());
    vfs.set("public/icon.svg", generateIconSvg(config));
    vfs.set("public/apple-touch-icon.svg", generateIconSvg(config));

  // 4. API Routes
  for (const [entityName, entityConfig] of Object.entries(config.entities)) {
    vfs.set(`src/app/api/${entityName}/route.ts`, generateApiRoute(entityName, entityConfig));
    vfs.set(`src/app/api/${entityName}/[id]/route.ts`, generateApiIdRoute(entityName));
  }

  // 5. Pages
  for (const page of config.pages) {
    if (page.type === "table" || page.type === "form") {
      const normalizedPath = page.path.replace(/^\//, "");
      vfs.set(`src/app/(pages)/${normalizedPath}/page.tsx`, generateEntityPage(page.name, page.entity!));
    }
  }

  // 6. Environment example and README + seed script
  vfs.set(".env.example", generateEnvExample());
  vfs.set("README.md", generateGeneratedReadme(config));
  vfs.set("prisma/seed.js", generatePrismaSeed(config));

  // 7. Manifest of generated files
  vfs.set("GENERATED_FILES.txt", Array.from(vfs.keys()).join("\n"));

  return vfs;
}

function generateEnvExample(): string {
  const lines = [
    '# Copy to .env and fill in your values',
    'DATABASE_URL="postgresql://user:password@localhost:5432/your_database"',
    'NEXTAUTH_SECRET="change-me"',
  ];
  return lines.join('\n') + '\n';
}

function generateGeneratedReadme(config: AppConfig): string {
  const lines = [
    `# ${config.app.name}`,
    '',
    'This project was generated by Antigravity AI.',
    '',
    'Quick start',
    '',
    '1. Copy .env.example to .env and set your DATABASE_URL.',
    '2. Install dependencies:',
    '',
    '   npm install',
    '',
    '3. Push the Prisma schema to your database and create tables:',
    '',
    '   npx prisma db push',
    '',
    '4. (Optional) Seed the database with example records:',
    '',
    '   node prisma/seed.js',
    '',
    '5. Run the dev server:',
    '',
    '   npm run dev',

      'PWA',

      '- The generated app includes a web manifest, installable icons, and a service worker.',
      '- Open the app in a supported browser to install it to your device or desktop.',
    '',
    'Notes',
    '- The Prisma schema is under prisma/schema.prisma.',
    '- prisma/seed.js will create one sample record per entity.',
  ];
  return lines.join('\n') + '\n';
}

function generatePrismaSeed(config: AppConfig): string {
  const lines: string[] = [
    "const { PrismaClient } = require('@prisma/client');",
    'const prisma = new PrismaClient();',
    '',
    'async function main() {',
  ];

  for (const [entityName, entityConfig] of Object.entries(config.entities)) {
    const modelName = entityName.charAt(0).toUpperCase() + entityName.slice(1);
    const sample: Record<string, any> = {};
    for (const [fieldName, field] of Object.entries(entityConfig.fields)) {
      if (field.type === 'number') sample[fieldName] = 1;
      else if (field.type === 'boolean') sample[fieldName] = false;
      else if (field.type === 'date') sample[fieldName] = new Date().toISOString();
      else sample[fieldName] = `${fieldName} example`;
    }

    lines.push(`  // Create sample for ${modelName}`);
    lines.push(`  await prisma.${modelName.toLowerCase()}.create({ data: ${JSON.stringify(sample)} });`);
    lines.push('');
  }

  lines.push("  console.log('Seed completed');");
  lines.push('}');
  lines.push('');
  lines.push('main()');
  lines.push('  .catch((e) => { console.error(e); process.exit(1); })');
  lines.push('  .finally(async () => { await prisma.$disconnect(); });');

  return lines.join('\n');
}

function generatePackageJson(config: AppConfig): string {
  return JSON.stringify({
    name: config.app.name.toLowerCase().replace(/\s+/g, "-"),
    version: "0.1.0",
    private: true,
    scripts: {
      "dev": "next dev",
      "build": "next build",
      "start": "next start",
      "lint": "next lint",
      "db:push": "prisma db push",
      "db:studio": "prisma studio"
    },
    dependencies: {
      "@prisma/client": "^5.22.0",
      "lucide-react": "^0.368.0",
      "next": "14.2.3",
      "react": "^18",
      "react-dom": "^18",
      "recharts": "^2.12.7"
    },
    devDependencies: {
      "@types/node": "^20",
      "@types/react": "^18",
      "@types/react-dom": "^18",
      "postcss": "^8",
      "prisma": "^5.22.0",
      "tailwindcss": "^3.4.1",
      "typescript": "^5"
    }
  }, null, 2);
}

function generateTsConfig(): string {
  return `{
  "compilerOptions": {
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./src/*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}`;
}

function generateTailwindConfig(): string {
  return `import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#3b82f6",
        background: "#ffffff",
      },
      boxShadow: {
        soft: "0 12px 40px rgba(0, 0, 0, 0.12)",
      },
    },
  },
  plugins: [],
};
export default config;`;
}

function generatePostcssConfig(): string {
  return `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};`;
}

function generateNextConfig(): string {
  return `/** @type {import('next').NextConfig} */
const nextConfig = {};
export default nextConfig;`;
}

function generateManifest(config: AppConfig): string {
  return JSON.stringify(
    {
      name: config.app.name,
      short_name: config.app.name.slice(0, 12),
      description: config.app.description || "Generated app",
      start_url: "/",
      scope: "/",
      display: "standalone",
      background_color: "#09090b",
      theme_color: config.app.theme?.primaryColor || "#6366f1",
      icons: [
        {
          src: "/icon.svg",
          sizes: "any",
          type: "image/svg+xml",
          purpose: "any maskable",
        },
      ],
    },
    null,
    2,
  );
}

function generateServiceWorker(): string {
  return `const CACHE_NAME = "antigravity-app-v1";
const ASSETS = ["/", "/manifest.webmanifest", "/icon.svg", "/apple-touch-icon.svg"];

self.addEventListener("install", (event) => {
  event.waitUntil(caches.open(CACHE_NAME).then((cache) => cache.addAll(ASSETS)));
  self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((key) => key !== CACHE_NAME).map((key) => caches.delete(key)))
    )
  );
  self.clients.claim();
});

self.addEventListener("fetch", (event) => {
  if (event.request.method !== "GET") return;
  event.respondWith(
    caches.match(event.request).then((cached) => {
      if (cached) return cached;
      return fetch(event.request)
        .then((response) => {
          const cloned = response.clone();
          caches.open(CACHE_NAME).then((cache) => cache.put(event.request, cloned));
          return response;
        })
        .catch(() => caches.match("/"));
    })
  );
});`;
}

function generateIconSvg(config: AppConfig): string {
  const label = config.app.name.slice(0, 2).toUpperCase();
  const accent = config.app.theme?.primaryColor || "#6366f1";
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" role="img" aria-label="${config.app.name}">
  <defs>
    <linearGradient id="g" x1="0" x2="1" y1="0" y2="1">
      <stop offset="0%" stop-color="${accent}"/>
      <stop offset="100%" stop-color="#0f172a"/>
    </linearGradient>
  </defs>
  <rect width="512" height="512" rx="112" fill="url(#g)"/>
  <rect x="88" y="88" width="336" height="336" rx="84" fill="rgba(255,255,255,0.08)" stroke="rgba(255,255,255,0.18)"/>
  <text x="50%" y="55%" dominant-baseline="middle" text-anchor="middle" font-family="Inter, Arial, sans-serif" font-size="160" font-weight="800" fill="#ffffff">${label}</text>
</svg>`;
}

function generatePwaRegister(): string {
  return `"use client";

import { useEffect } from "react";

export default function PwaRegister() {
  useEffect(() => {
    if (!("serviceWorker" in navigator)) return;
    navigator.serviceWorker.register("/sw.js").catch(() => {
      // Ignore install-time failures in unsupported browsers.
    });
  }, []);

  return null;
}`;
}

function generatePrismaSchema(config: AppConfig): string {
  let schema = `generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

`;

  for (const [entityName, entityConfig] of Object.entries(config.entities)) {
    // Capitalize first letter
    const modelName = entityName.charAt(0).toUpperCase() + entityName.slice(1);
    schema += `model ${modelName} {\n`;
    schema += `  id String @id @default(uuid())\n`;
    
    for (const [fieldName, field] of Object.entries(entityConfig.fields)) {
      let type = "String";
      if (field.type === "number") type = "Int";
      if (field.type === "boolean") type = "Boolean";
      if (field.type === "date") type = "DateTime";
      
      const optional = field.required ? "" : "?";
      schema += `  ${fieldName} ${type}${optional}\n`;
    }
    
    schema += `  createdAt DateTime @default(now())\n`;
    schema += `  updatedAt DateTime @updatedAt\n`;
    schema += `}\n\n`;
  }

  return schema;
}

function generatePrismaClient(): string {
  return `import { PrismaClient } from '@prisma/client'

const prismaClientSingleton = () => {
  return new PrismaClient()
}

declare global {
  var prismaGlobal: undefined | ReturnType<typeof prismaClientSingleton>
}

const prisma = globalThis.prismaGlobal ?? prismaClientSingleton()

export default prisma

if (process.env.NODE_ENV !== 'production') globalThis.prismaGlobal = prisma`;
}

function generateGlobalsCss(): string {
  return `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  color-scheme: dark;
}

html {
  scroll-behavior: smooth;
}

body {
  min-height: 100vh;
  background:
    radial-gradient(circle at top, rgba(99, 102, 241, 0.12), transparent 36%),
    linear-gradient(180deg, #020617 0%, #0f172a 100%);
  color: #e5e7eb;
}

* {
  box-sizing: border-box;
}

::selection {
  background: rgba(99, 102, 241, 0.35);
  color: white;
}`;
}

function generateRootLayout(config: AppConfig): string {
  const pages = config.pages.map((page) => ({ name: page.name, path: page.path }));
  const desktopLinks = pages
    .map((page) => `              <Link href="${page.path}" className="flex items-center rounded-xl px-4 py-3 text-sm font-medium text-slate-300 transition hover:bg-white/5 hover:text-white">${page.name}</Link>`)
    .join("\n");
  const mobileLinks = pages
    .slice(0, 4)
    .map((page) => `                <Link href="${page.path}" className="flex flex-col items-center justify-center rounded-2xl px-2 py-2 text-[10px] font-medium text-slate-300 transition active:scale-[0.98]">${page.name}</Link>`)
    .join("\n");
  const topLinks = pages
    .map((page) => `                <Link href="${page.path}" className="whitespace-nowrap rounded-full border border-white/10 bg-white/5 px-4 py-2 text-xs font-medium text-slate-200">${page.name}</Link>`)
    .join("\n");

  return `import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import PwaRegister from "@/components/PwaRegister";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "${config.app.name}",
  description: "Generated by Antigravity AI",
  manifest: "/manifest.webmanifest",
  appleWebApp: {
    capable: true,
    title: "${config.app.name}",
    statusBarStyle: "default",
  },
  themeColor: "${config.app.theme?.primaryColor || "#6366f1"}",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " bg-slate-950 text-slate-100 antialiased"}>
        <PwaRegister />
        <div className="min-h-screen md:flex">
          <aside className="hidden md:flex md:w-72 md:flex-col md:border-r md:border-white/10 md:bg-slate-950/80 md:backdrop-blur-xl">
            <div className="border-b border-white/10 p-6">
              <p className="text-xs font-semibold uppercase tracking-[0.35em] text-indigo-300/70">Antigravity AI</p>
              <h1 className="mt-3 text-2xl font-bold text-white">${config.app.name}</h1>
              <p className="mt-2 text-sm leading-6 text-slate-400">${config.app.description || "A responsive app generated from your configuration."}</p>
            </div>
            <nav className="flex-1 space-y-1 px-3 py-4">
${desktopLinks}
            </nav>
          </aside>

          <div className="flex min-h-screen flex-1 flex-col">
            <header className="sticky top-0 z-30 border-b border-white/10 bg-slate-950/85 px-4 py-3 backdrop-blur-xl md:hidden">
              <div className="flex items-center justify-between gap-3">
                <div>
                  <p className="text-[10px] font-semibold uppercase tracking-[0.3em] text-indigo-300/70">Antigravity AI</p>
                  <h1 className="text-base font-semibold text-white">${config.app.name}</h1>
                </div>
                <span className="rounded-full border border-white/10 bg-white/5 px-3 py-1 text-[10px] font-semibold uppercase tracking-[0.2em] text-slate-300">PWA ready</span>
              </div>
              <nav className="mt-3 flex gap-2 overflow-x-auto pb-1 no-scrollbar">
${topLinks}
              </nav>
            </header>

            <main className="flex-1 px-4 py-5 pb-[calc(5.5rem+env(safe-area-inset-bottom))] md:px-8 md:py-8">
              <div className="mx-auto w-full max-w-7xl">{children}</div>
            </main>

            <nav className="fixed inset-x-0 bottom-0 z-40 border-t border-white/10 bg-slate-950/90 px-2 py-2 backdrop-blur-xl md:hidden">
              <div className="grid grid-cols-4 gap-2">
${mobileLinks}
              </div>
            </nav>
          </div>
        </div>
      </body>
    </html>
  );
}`;
}

function generateHomePage(config: AppConfig): string {
  return `export default function Home() {
  return (
    <div className="space-y-6">
      <section className="rounded-3xl border border-white/10 bg-white/5 p-6 shadow-soft backdrop-blur-xl md:p-8">
        <p className="text-[10px] font-semibold uppercase tracking-[0.35em] text-indigo-300/70">Overview</p>
        <div className="mt-3 flex flex-col gap-4 md:flex-row md:items-end md:justify-between">
          <div className="max-w-2xl">
            <h1 className="text-3xl font-bold tracking-tight text-white md:text-5xl">${config.app.name}</h1>
            <p className="mt-4 text-sm leading-7 text-slate-300 md:text-base">${config.app.description || 'Welcome to your generated app.'}</p>
          </div>
          <div className="grid grid-cols-2 gap-3 text-sm md:min-w-80">
            <div className="rounded-2xl border border-white/10 bg-slate-950/60 p-4">
              <div className="text-slate-400">Responsive</div>
              <div className="mt-1 font-semibold text-white">Mobile first</div>
            </div>
            <div className="rounded-2xl border border-white/10 bg-slate-950/60 p-4">
              <div className="text-slate-400">Installable</div>
              <div className="mt-1 font-semibold text-white">PWA ready</div>
            </div>
          </div>
        </div>
      </section>
      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        <div className="rounded-2xl border border-white/10 bg-slate-950/60 p-5">
          <p className="text-sm text-slate-400">Fast setup</p>
          <p className="mt-2 text-lg font-semibold text-white">Generate, deploy, install</p>
        </div>
        <div className="rounded-2xl border border-white/10 bg-slate-950/60 p-5">
          <p className="text-sm text-slate-400">Responsive layout</p>
          <p className="mt-2 text-lg font-semibold text-white">Sidebar on desktop, bottom nav on mobile</p>
        </div>
        <div className="rounded-2xl border border-white/10 bg-slate-950/60 p-5">
          <p className="text-sm text-slate-400">Offline ready</p>
          <p className="mt-2 text-lg font-semibold text-white">Manifest + service worker</p>
        </div>
        <div className="rounded-2xl border border-white/10 bg-slate-950/60 p-5">
          <p className="text-sm text-slate-400">Data driven</p>
          <p className="mt-2 text-lg font-semibold text-white">Entity pages scale to your config</p>
        </div>
      </div>
    </div>
  );
}`;
}

function generateApiRoute(entityName: string, entityConfig: EntityConfig): string {
  const modelName = entityName.charAt(0).toUpperCase() + entityName.slice(1);
  return `import { NextResponse } from "next/server";
import prisma from "@/lib/prisma";

export async function GET(request: Request) {
  try {
    const records = await prisma.${modelName.toLowerCase()}.findMany({
      orderBy: { createdAt: "desc" }
    });
    return NextResponse.json({ success: true, data: records });
  } catch (error) {
    return NextResponse.json({ success: false, error: "Failed to fetch data" }, { status: 500 });
  }
}

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const record = await prisma.${modelName.toLowerCase()}.create({
      data: body
    });
    return NextResponse.json({ success: true, data: record }, { status: 201 });
  } catch (error) {
    return NextResponse.json({ success: false, error: "Failed to create record" }, { status: 500 });
  }
}`;
}

function generateApiIdRoute(entityName: string): string {
  const modelName = entityName.charAt(0).toUpperCase() + entityName.slice(1);
  return `import { NextResponse } from "next/server";
import prisma from "@/lib/prisma";

export async function GET(request: Request, { params }: { params: { id: string } }) {
  try {
    const record = await prisma.${modelName.toLowerCase()}.findUnique({
      where: { id: params.id }
    });
    if (!record) return NextResponse.json({ success: false, error: "Not found" }, { status: 404 });
    return NextResponse.json({ success: true, data: record });
  } catch (error) {
    return NextResponse.json({ success: false, error: "Failed to fetch record" }, { status: 500 });
  }
}

export async function PUT(request: Request, { params }: { params: { id: string } }) {
  try {
    const body = await request.json();
    const record = await prisma.${modelName.toLowerCase()}.update({
      where: { id: params.id },
      data: body
    });
    return NextResponse.json({ success: true, data: record });
  } catch (error) {
    return NextResponse.json({ success: false, error: "Failed to update record" }, { status: 500 });
  }
}

export async function DELETE(request: Request, { params }: { params: { id: string } }) {
  try {
    await prisma.${modelName.toLowerCase()}.delete({
      where: { id: params.id }
    });
    return NextResponse.json({ success: true, data: { message: "Deleted" } });
  } catch (error) {
    return NextResponse.json({ success: false, error: "Failed to delete record" }, { status: 500 });
  }
}`;
}

function generateEntityPage(pageName: string, entityName: string): string {
  return `"use client";
import { useEffect, useMemo, useState } from "react";
import { Search, Plus, MoreHorizontal } from "lucide-react";

export default function Page() {
  const [data, setData] = useState([]);
  const [loading, setLoading] = useState(true);
  const [query, setQuery] = useState("");

  useEffect(() => {
    fetch("/api/${entityName}")
      .then(res => res.json())
      .then(json => {
        if (json.success) setData(json.data);
        setLoading(false);
      });
  }, []);

  const filteredData = useMemo(() => {
    if (!query) return data;
    const search = query.toLowerCase();
    return data.filter((row: any) =>
      Object.values(row).some((value) => String(value).toLowerCase().includes(search))
    );
  }, [data, query]);

  return (
    <div className="space-y-6">
      <section className="rounded-3xl border border-white/10 bg-white/5 p-5 shadow-soft backdrop-blur-xl md:p-6">
        <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
          <div>
            <p className="text-[10px] font-semibold uppercase tracking-[0.35em] text-indigo-300/70">${pageName}</p>
            <h1 className="mt-2 text-2xl font-bold text-white md:text-4xl">${pageName}</h1>
          </div>
          <div className="flex flex-col gap-3 sm:flex-row">
            <label className="flex min-w-0 items-center gap-2 rounded-2xl border border-white/10 bg-slate-950/60 px-4 py-3 text-sm text-slate-300">
              <Search className="h-4 w-4 text-slate-400" />
              <input
                value={query}
                onChange={(e) => setQuery(e.target.value)}
                placeholder="Search records"
                className="w-full bg-transparent outline-none placeholder:text-slate-500"
              />
            </label>
            <button className="inline-flex items-center justify-center gap-2 rounded-2xl bg-indigo-500 px-4 py-3 text-sm font-semibold text-white shadow-lg shadow-indigo-500/20 transition hover:bg-indigo-400 active:scale-[0.98]">
              <Plus className="h-4 w-4" />
              Add
            </button>
          </div>
        </div>
      </section>

      <div className="rounded-3xl border border-white/10 bg-slate-950/60 shadow-soft overflow-hidden">
        {loading ? (
          <div className="p-8 text-center text-slate-400">Loading data...</div>
        ) : filteredData.length === 0 ? (
          <div className="p-8 text-center text-slate-400">No records found.</div>
        ) : (
          <>
            <div className="hidden overflow-x-auto md:block">
              <table className="w-full border-collapse text-left">
                <thead>
                  <tr className="border-b border-white/10 bg-white/[0.03]">
                    {Object.keys(filteredData[0]).filter(k => k !== 'id').map(key => (
                      <th key={key} className="p-4 text-xs font-semibold uppercase tracking-[0.2em] text-slate-400">{key}</th>
                    ))}
                    <th className="p-4 text-xs font-semibold uppercase tracking-[0.2em] text-slate-400"><MoreHorizontal className="h-4 w-4" /></th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-white/5">
                  {filteredData.map((row: any) => (
                    <tr key={row.id} className="transition hover:bg-white/[0.03]">
                      {Object.keys(row).filter(k => k !== 'id').map(key => (
                        <td key={key} className="p-4 text-sm text-slate-300">{String(row[key])}</td>
                      ))}
                      <td className="p-4 text-slate-500">
                        <MoreHorizontal className="h-4 w-4" />
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            <div className="grid gap-3 p-3 md:hidden">
              {filteredData.map((row: any) => (
                <article key={row.id} className="rounded-2xl border border-white/10 bg-slate-950/70 p-4">
                  {Object.keys(row).filter(k => k !== 'id').map(key => (
                    <div key={key} className="mb-3 last:mb-0">
                      <div className="text-[10px] font-semibold uppercase tracking-[0.2em] text-slate-500">{key}</div>
                      <div className="mt-1 break-words text-sm text-slate-200">{String(row[key])}</div>
                    </div>
                  ))}
                </article>
              ))}
            </div>
          </>
        )}
      </div>
    </div>
  );
}`;
}
