import { AppConfig, EntityConfig, TablePageConfig, FormPageConfig, DashboardPageConfig, DetailPageConfig } from "../shared/types";

// ============================================================
// Code Generator Service — Generates a full Next.js + Prisma
// codebase from a JSON AppConfig.
// ============================================================

export type VirtualFileSystem = Map<string, string>;

export function generateCodebase(config: AppConfig): VirtualFileSystem {
  const vfs = new Map<string, string>();

  // 1. Configs
  vfs.set("package.json", generatePackageJson(config));
  vfs.set("tsconfig.json", generateTsConfig());
  vfs.set("tailwind.config.ts", generateTailwindConfig());
  vfs.set("postcss.config.js", generatePostcssConfig());
  vfs.set("next.config.js", generateNextConfig());

  // 2. Database
  vfs.set("prisma/schema.prisma", generatePrismaSchema(config));
  vfs.set("src/lib/prisma.ts", generatePrismaClient());

  // 3. App Core
  vfs.set("src/app/globals.css", generateGlobalsCss());
  vfs.set("src/app/layout.tsx", generateRootLayout(config));
  vfs.set("src/app/page.tsx", generateHomePage(config));
  vfs.set("src/app/auth/page.tsx", generateAuthPage(config));
  vfs.set("src/app/api/auth/providers/route.ts", generateAuthProvidersRoute(config));
    vfs.set("src/components/PwaRegister.tsx", generatePwaRegister());

    // 3b. PWA assets
    vfs.set("src/app/manifest.ts", generateManifest(config));
    vfs.set("public/sw.js", generateServiceWorker());
    vfs.set("public/icon.svg", generateIconSvg(config));
    vfs.set("public/apple-touch-icon.svg", generateIconSvg(config));

  // 4. API Routes
  for (const [entityName, entityConfig] of Object.entries(config.entities)) {
    vfs.set(`src/app/api/${entityName}/route.ts`, generateApiRoute(entityName, entityConfig));
    vfs.set(`src/app/api/${entityName}/[id]/route.ts`, generateApiIdRoute(entityName));
  }

  // 5. Pages
  for (const page of config.pages) {
    const normalizedPath = page.path.replace(/^\//, "");
    if (page.type === "table") {
      vfs.set(`src/app/(pages)/${normalizedPath}/page.tsx`, generateTablePage(page, config.entities[page.entity]));
    }

    if (page.type === "form") {
      vfs.set(`src/app/(pages)/${normalizedPath}/page.tsx`, generateFormPage(page, config.entities[page.entity]));
    }

    if (page.type === "dashboard") {
      vfs.set(`src/app/(pages)/${normalizedPath}/page.tsx`, generateDashboardPage(page));
    }

    if (page.type === "detail") {
      vfs.set(`src/app/(pages)/${normalizedPath}/page.tsx`, generateDetailPage(page));
    }
  }

  // 6. Environment example and README + seed script
  vfs.set(".env.example", generateEnvExample());
  vfs.set("README.md", generateGeneratedReadme(config));
  vfs.set("prisma/seed.js", generatePrismaSeed(config));

  // 7. Manifest of generated files
  vfs.set("GENERATED_FILES.txt", Array.from(vfs.keys()).join("\n"));

  return vfs;
}

function generateEnvExample(): string {
  const lines = [
    '# Copy to .env and fill in your values',
    'DATABASE_URL="postgresql://user:password@localhost:5432/your_database"',
    'NEXTAUTH_SECRET="change-me"',
    'GOOGLE_CLIENT_ID="your-google-client-id"',
    'GOOGLE_CLIENT_SECRET="your-google-client-secret"',
    'GITHUB_CLIENT_ID="your-github-client-id"',
    'GITHUB_CLIENT_SECRET="your-github-client-secret"',
  ];
  return lines.join('\n') + '\n';
}

function generateGeneratedReadme(config: AppConfig): string {
  const lines = [
    `# ${config.app.name}`,
    '',
    'This project was generated by ConfigFlow.',
    '',
    'Quick start',
    '',
    '1. Copy .env.example to .env and set your DATABASE_URL.',
    '2. Install dependencies:',
    '',
    '   npm install',
    '',
    '3. Push the Prisma schema to your database and create tables:',
    '',
    '   npx prisma db push',
    '',
    '4. (Optional) Seed the database with example records:',
    '',
    '   node prisma/seed.js',
    '',
    '5. Run the dev server:',
    '',
    '   npm run dev',

      'PWA',

      '- The generated app includes a web manifest, installable icons, and a service worker.',
      '- Open the app in a supported browser to install it to your device or desktop.',
    '',
    'Notes',
    '- The Prisma schema is under prisma/schema.prisma.',
    '- prisma/seed.js will create one sample record per entity.',
  ];
  return lines.join('\n') + '\n';
}

function generatePrismaSeed(config: AppConfig): string {
  const lines: string[] = [
    "const { PrismaClient } = require('@prisma/client');",
    'const prisma = new PrismaClient();',
    '',
    'async function main() {',
  ];

  for (const [entityName, entityConfig] of Object.entries(config.entities)) {
    const modelName = entityName.charAt(0).toUpperCase() + entityName.slice(1);
    const sample: Record<string, any> = {};
    for (const [fieldName, field] of Object.entries(entityConfig.fields)) {
      if (field.type === 'number') sample[fieldName] = 1;
      else if (field.type === 'boolean') sample[fieldName] = false;
      else if (field.type === 'date') sample[fieldName] = new Date().toISOString();
      else sample[fieldName] = `${fieldName} example`;
    }

    lines.push(`  // Create sample for ${modelName}`);
    lines.push(`  await prisma.${modelName.toLowerCase()}.create({ data: ${JSON.stringify(sample)} });`);
    lines.push('');
  }

  lines.push("  console.log('Seed completed');");
  lines.push('}');
  lines.push('');
  lines.push('main()');
  lines.push('  .catch((e) => { console.error(e); process.exit(1); })');
  lines.push('  .finally(async () => { await prisma.$disconnect(); });');

  return lines.join('\n');
}

function generatePackageJson(config: AppConfig): string {
  return JSON.stringify({
    name: config.app.name.toLowerCase().replace(/\s+/g, "-"),
    version: "0.1.0",
    private: true,
    scripts: {
      "dev": "next dev",
      "build": "next build",
      "start": "next start",
      "lint": "next lint",
      "db:push": "prisma db push",
      "db:studio": "prisma studio"
    },
    dependencies: {
      "@prisma/client": "^5.22.0",
      "lucide-react": "^0.368.0",
      "next": "14.2.3",
      "react": "^18",
      "react-dom": "^18",
      "recharts": "^2.12.7"
    },
    devDependencies: {
      "@types/node": "^20",
      "@types/react": "^18",
      "@types/react-dom": "^18",
      "postcss": "^8",
      "prisma": "^5.22.0",
      "tailwindcss": "^3.4.1",
      "typescript": "^5"
    }
  }, null, 2);
}

function generateTsConfig(): string {
  return `{
  "compilerOptions": {
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./src/*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}`;
}

function generateTailwindConfig(): string {
  return `import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#3b82f6",
        background: "#ffffff",
      },
      boxShadow: {
        soft: "0 12px 40px rgba(0, 0, 0, 0.12)",
      },
    },
  },
  plugins: [],
};
export default config;`;
}

function generateTablePage(page: TablePageConfig, entityConfig?: EntityConfig): string {
  const columns = page.columns.length > 0 ? page.columns : Object.keys(entityConfig?.fields || {});
  const searchable = page.searchable !== false;
  const actions = page.actions || [];

  return `"use client";
import { useEffect, useMemo, useState } from "react";
import { Search, Plus, MoreHorizontal } from "lucide-react";

const columns = ${JSON.stringify(columns)};

export default function Page() {
  const [data, setData] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [query, setQuery] = useState("");

  useEffect(() => {
    fetch("/api/${page.entity}")
      .then((res) => res.json())
      .then((json) => {
        if (json.success) setData(json.data);
        setLoading(false);
      })
      .catch(() => setLoading(false));
  }, []);

  const filteredData = useMemo(() => {
    if (!query) return data;
    const search = query.toLowerCase();
    return data.filter((row) =>
      Object.values(row).some((value) => String(value).toLowerCase().includes(search))
    );
  }, [data, query]);

  const canEdit = ${actions.includes("edit")};
  const canDelete = ${actions.includes("delete")};

  return (
    <div className="space-y-6">
      <section className="rounded-3xl border border-white/10 bg-white/5 p-5 shadow-soft backdrop-blur-xl md:p-6">
        <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
          <div>
            <p className="text-[10px] font-semibold uppercase tracking-[0.35em] text-indigo-300/70">${page.name}</p>
            <h1 className="mt-2 text-2xl font-bold text-white md:text-4xl">${page.name}</h1>
          </div>
          <div className="flex flex-col gap-3 sm:flex-row">
            ${searchable ? `<label className="flex min-w-0 items-center gap-2 rounded-2xl border border-white/10 bg-slate-950/60 px-4 py-3 text-sm text-slate-300">
              <Search className="h-4 w-4 text-slate-400" />
              <input
                value={query}
                onChange={(e) => setQuery(e.target.value)}
                placeholder="Search records"
                className="w-full bg-transparent outline-none placeholder:text-slate-500"
              />
            </label>` : ""}
            ${actions.includes("create") ? `<button className="inline-flex items-center justify-center gap-2 rounded-2xl bg-indigo-500 px-4 py-3 text-sm font-semibold text-white shadow-lg shadow-indigo-500/20 transition hover:bg-indigo-400 active:scale-[0.98]"><Plus className="h-4 w-4" />Add</button>` : ""}
          </div>
        </div>
      </section>

      <div className="rounded-3xl border border-white/10 bg-slate-950/60 shadow-soft overflow-hidden">
        {loading ? (
          <div className="p-8 text-center text-slate-400">Loading data...</div>
        ) : filteredData.length === 0 ? (
          <div className="p-8 text-center text-slate-400">No records found.</div>
        ) : (
          <>
            <div className="hidden overflow-x-auto md:block">
              <table className="w-full border-collapse text-left">
                <thead>
                  <tr className="border-b border-white/10 bg-white/[0.03]">
                    {columns.map((key) => (
                      <th key={key} className="p-4 text-xs font-semibold uppercase tracking-[0.2em] text-slate-400">{key}</th>
                    ))}
                    {(canEdit || canDelete) && <th className="p-4 text-xs font-semibold uppercase tracking-[0.2em] text-slate-400"><MoreHorizontal className="h-4 w-4" /></th>}
                  </tr>
                </thead>
                <tbody className="divide-y divide-white/5">
                  {filteredData.map((row) => (
                    <tr key={row.id} className="transition hover:bg-white/[0.03]">
                      {columns.map((key) => (
                        <td key={key} className="p-4 text-sm text-slate-300">{String(row[key] ?? "—")}</td>
                      ))}
                      {(canEdit || canDelete) && (
                        <td className="p-4 text-slate-500"><MoreHorizontal className="h-4 w-4" /></td>
                      )}
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            <div className="grid gap-3 p-3 md:hidden">
              {filteredData.map((row) => (
                <article key={row.id} className="rounded-2xl border border-white/10 bg-slate-950/70 p-4">
                  {columns.map((key) => (
                    <div key={key} className="mb-3 last:mb-0">
                      <div className="text-[10px] font-semibold uppercase tracking-[0.2em] text-slate-500">{key}</div>
                      <div className="mt-1 break-words text-sm text-slate-200">{String(row[key] ?? "—")}</div>
                    </div>
                  ))}
                </article>
              ))}
            </div>
          </>
        )}
      </div>
    </div>
  );
}`;
}

function generateFormPage(page: FormPageConfig, entityConfig?: EntityConfig): string {
  const fieldNames = page.fields && page.fields.length > 0 ? page.fields : Object.keys(entityConfig?.fields || {});
  const fieldMeta = fieldNames.map((fieldName) => {
    const field = (entityConfig?.fields[fieldName] || { type: "string" }) as any;
    return {
      name: fieldName,
      type: field.type,
      required: Boolean(field.required),
      label: field.label || fieldName,
      placeholder: field.placeholder || "",
      options: field.options || [],
    };
  });

  return `"use client";
import { useEffect, useState } from "react";
import { CheckCircle2, Loader2 } from "lucide-react";

const fields = ${JSON.stringify(fieldMeta, null, 2)};

export default function Page() {
  const [formData, setFormData] = useState<Record<string, unknown>>({});
  const [submitting, setSubmitting] = useState(false);
  const [success, setSuccess] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const initial: Record<string, unknown> = {};
    for (const field of fields) initial[field.name] = "";
    setFormData(initial);
  }, []);

  const handleSubmit = async (event: React.FormEvent) => {
    event.preventDefault();
    setSubmitting(true);
    setError(null);

    try {
      const response = await fetch("/api/${page.entity}", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(formData),
      });

      if (!response.ok) throw new Error("Failed to create record");
      setSuccess(true);
    } catch (err: any) {
      setError(err?.message || "Failed to submit form");
    } finally {
      setSubmitting(false);
    }
  };

  if (success) {
        <CheckCircle2 className="h-14 w-14 text-emerald-400" />
        <p className="text-lg text-white/80">Saved successfully.</p>
      </div>
    );
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      <section className="rounded-3xl border border-white/10 bg-white/5 p-5 shadow-soft backdrop-blur-xl md:p-6">
        <p className="text-[10px] font-semibold uppercase tracking-[0.35em] text-indigo-300/70">${page.name}</p>
        <h1 className="mt-2 text-2xl font-bold text-white md:text-4xl">${page.name}</h1>
      </section>

      {error && <div className="rounded-2xl border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-300">{error}</div>}

      <div className="grid gap-4 md:grid-cols-2">
        {fields.map((field) => (
          <label key={field.name} className="space-y-2 rounded-2xl border border-white/10 bg-slate-950/60 p-4">
            <span className="block text-sm font-medium text-slate-200">{field.label}{field.required ? " *" : ""}</span>
            {field.type === "text" ? (
              <textarea
                value={String(formData[field.name] ?? "")}
                onChange={(e) => setFormData((prev) => ({ ...prev, [field.name]: e.target.value }))}
                placeholder={field.placeholder}
                rows={4}
                className="w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-white outline-none placeholder:text-slate-500"
              />
            ) : field.type === "boolean" ? (
              <select
                value={String(formData[field.name] ?? "")}
                onChange={(e) => setFormData((prev) => ({ ...prev, [field.name]: e.target.value === "true" }))}
                className="w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-white outline-none"
              >
                <option value="">Select</option>
                <option value="true">True</option>
                <option value="false">False</option>
              </select>
            ) : field.type === "enum" ? (
              <select
                value={String(formData[field.name] ?? "")}
                onChange={(e) => setFormData((prev) => ({ ...prev, [field.name]: e.target.value }))}
                className="w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-white outline-none"
              >
                <option value="">Select</option>
                {field.options.map((option) => <option key={option} value={option}>{option}</option>)}
              </select>
            ) : (
              <input
                value={String(formData[field.name] ?? "")}
                onChange={(e) => setFormData((prev) => ({ ...prev, [field.name]: e.target.value }))}
                placeholder={field.placeholder}
                className="w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-white outline-none placeholder:text-slate-500"
              />
            )}
          </label>
        ))}
      </div>

      <button disabled={submitting} className="inline-flex items-center justify-center gap-2 rounded-2xl bg-indigo-500 px-5 py-3 text-sm font-semibold text-white shadow-lg shadow-indigo-500/20 transition hover:bg-indigo-400 disabled:opacity-60">
        {submitting ? <Loader2 className="h-4 w-4 animate-spin" /> : null}
        {submitting ? "Saving..." : "Save"}
      </button>
    </form>
  );
}`;
}
function generatePostcssConfig(): string {
  return `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};`;
}

function generateNextConfig(): string {
  return `/** @type {import('next').NextConfig} */
const nextConfig = {};
export default nextConfig;`;
}

function generateManifest(config: AppConfig): string {
  return JSON.stringify(
    {
      name: config.app.name,
      short_name: config.app.name.slice(0, 12),
      description: config.app.description || "Generated app",
      start_url: "/",
      scope: "/",
      display: "standalone",
      background_color: "#09090b",
      theme_color: config.app.theme?.primaryColor || "#6366f1",
      icons: [
        {
          src: "/icon.svg",
          sizes: "any",
          type: "image/svg+xml",
          purpose: "any maskable",
        },
      ],
    },
    null,
    2,
  );
}

function generateServiceWorker(): string {
  return `const CACHE_NAME = "antigravity-app-v1";
const ASSETS = ["/", "/manifest.webmanifest", "/icon.svg", "/apple-touch-icon.svg"];

self.addEventListener("install", (event) => {
  event.waitUntil(caches.open(CACHE_NAME).then((cache) => cache.addAll(ASSETS)));
  self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((key) => key !== CACHE_NAME).map((key) => caches.delete(key)))
    )
  );
  self.clients.claim();
});

self.addEventListener("fetch", (event) => {
  if (event.request.method !== "GET") return;
  event.respondWith(
    caches.match(event.request).then((cached) => {
      if (cached) return cached;
      return fetch(event.request)
        .then((response) => {
          const cloned = response.clone();
          caches.open(CACHE_NAME).then((cache) => cache.put(event.request, cloned));
          return response;
        })
        .catch(() => caches.match("/"));
    })
  );
});`;
}

function generateIconSvg(config: AppConfig): string {
  const label = config.app.name.slice(0, 2).toUpperCase();
  const accent = config.app.theme?.primaryColor || "#6366f1";
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" role="img" aria-label="${config.app.name}">
  <defs>
    <linearGradient id="g" x1="0" x2="1" y1="0" y2="1">
      <stop offset="0%" stop-color="${accent}"/>
      <stop offset="100%" stop-color="#0f172a"/>
    </linearGradient>
  function generateDetailPage(page: DetailPageConfig): string {
  <rect width="512" height="512" rx="112" fill="url(#g)"/>
  <rect x="88" y="88" width="336" height="336" rx="84" fill="rgba(255,255,255,0.08)" stroke="rgba(255,255,255,0.18)"/>
  <text x="50%" y="55%" dominant-baseline="middle" text-anchor="middle" font-family="Inter, Arial, sans-serif" font-size="160" font-weight="800" fill="#ffffff">${label}</text>
</svg>`;
}

function generatePwaRegister(): string {
  return `"use client";

import { useEffect } from "react";

export default function PwaRegister() {
  useEffect(() => {
    if (!("serviceWorker" in navigator)) return;
    navigator.serviceWorker.register("/sw.js").catch(() => {
      // Ignore install-time failures in unsupported browsers.
    });
  }, []);

  return null;
}`;
}

function generatePrismaSchema(config: AppConfig): string {
  let schema = `generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

`;

  for (const [entityName, entityConfig] of Object.entries(config.entities)) {
    // Capitalize first letter
    const modelName = entityName.charAt(0).toUpperCase() + entityName.slice(1);
    schema += `model ${modelName} {\n`;
    schema += `  id String @id @default(uuid())\n`;
    
    for (const [fieldName, field] of Object.entries(entityConfig.fields)) {
      let type = "String";
      if (field.type === "number") type = "Int";
      if (field.type === "boolean") type = "Boolean";
      if (field.type === "date") type = "DateTime";
      
      const optional = field.required ? "" : "?";
      schema += `  ${fieldName} ${type}${optional}\n`;
    }
    
    schema += `  createdAt DateTime @default(now())\n`;
    schema += `  updatedAt DateTime @updatedAt\n`;
    schema += `}\n\n`;
  }

  return schema;
}

function generatePrismaClient(): string {
  return `import { PrismaClient } from '@prisma/client'

const prismaClientSingleton = () => {
  return new PrismaClient()
}

declare global {
  var prismaGlobal: undefined | ReturnType<typeof prismaClientSingleton>
}

const prisma = globalThis.prismaGlobal ?? prismaClientSingleton()

export default prisma

if (process.env.NODE_ENV !== 'production') globalThis.prismaGlobal = prisma`;
}

function generateGlobalsCss(): string {
  return `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  color-scheme: dark;
}

html {
  scroll-behavior: smooth;
}

body {
  min-height: 100vh;
  background:
    radial-gradient(circle at top, rgba(99, 102, 241, 0.12), transparent 36%),
    linear-gradient(180deg, #020617 0%, #0f172a 100%);
  color: #e5e7eb;
}

* {
  box-sizing: border-box;
}

::selection {
  background: rgba(99, 102, 241, 0.35);
  color: white;
}`;
}

function generateRootLayout(config: AppConfig): string {
  const pages = config.pages.map((page) => ({ name: page.name, path: page.path }));
  const desktopLinks = pages
    .map((page) => `              <Link href="${page.path}" className="flex items-center rounded-xl px-4 py-3 text-sm font-medium text-slate-300 transition hover:bg-white/5 hover:text-white">${page.name}</Link>`)
    .join("\n");
  const mobileLinks = pages
    .slice(0, 4)
    .map((page) => `                <Link href="${page.path}" className="flex flex-col items-center justify-center rounded-2xl px-2 py-2 text-[10px] font-medium text-slate-300 transition active:scale-[0.98]">${page.name}</Link>`)
    .join("\n");
  const topLinks = pages
    .map((page) => `                <Link href="${page.path}" className="whitespace-nowrap rounded-full border border-white/10 bg-white/5 px-4 py-2 text-xs font-medium text-slate-200">${page.name}</Link>`)
    .join("\n");

  return `import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import PwaRegister from "@/components/PwaRegister";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "${config.app.name}",
  description: "Generated by ConfigFlow",
  manifest: "/manifest.webmanifest",
  appleWebApp: {
    capable: true,
    title: "${config.app.name}",
    statusBarStyle: "default",
  },
  themeColor: "${config.app.theme?.primaryColor || "#6366f1"}",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " bg-slate-950 text-slate-100 antialiased"}>
        <PwaRegister />
        <div className="min-h-screen md:flex">
          <aside className="hidden md:flex md:w-72 md:flex-col md:border-r md:border-white/10 md:bg-slate-950/80 md:backdrop-blur-xl">
            <div className="border-b border-white/10 p-6">
              <p className="text-xs font-semibold uppercase tracking-[0.35em] text-indigo-300/70">ConfigFlow</p>
              <h1 className="mt-3 text-2xl font-bold text-white">${config.app.name}</h1>
              <p className="mt-2 text-sm leading-6 text-slate-400">${config.app.description || "A responsive app generated from your configuration."}</p>
            </div>
            <nav className="flex-1 space-y-1 px-3 py-4">
${desktopLinks}
            </nav>
          </aside>

          <div className="flex min-h-screen flex-1 flex-col">
            <header className="sticky top-0 z-30 border-b border-white/10 bg-slate-950/85 px-4 py-3 backdrop-blur-xl md:hidden">
              <div className="flex items-center justify-between gap-3">
                <div>
                  <p className="text-[10px] font-semibold uppercase tracking-[0.3em] text-indigo-300/70">ConfigFlow</p>
                  <h1 className="text-base font-semibold text-white">${config.app.name}</h1>
                </div>
                <span className="rounded-full border border-white/10 bg-white/5 px-3 py-1 text-[10px] font-semibold uppercase tracking-[0.2em] text-slate-300">PWA ready</span>
              </div>
              <nav className="mt-3 flex gap-2 overflow-x-auto pb-1 no-scrollbar">
${topLinks}
              </nav>
            </header>

            <main className="flex-1 px-4 py-5 pb-[calc(5.5rem+env(safe-area-inset-bottom))] md:px-8 md:py-8">
              <div className="mx-auto w-full max-w-7xl">{children}</div>
            </main>

            <nav className="fixed inset-x-0 bottom-0 z-40 border-t border-white/10 bg-slate-950/90 px-2 py-2 backdrop-blur-xl md:hidden">
              <div className="grid grid-cols-4 gap-2">
${mobileLinks}
              </div>
            </nav>
          </div>
        </div>
      </body>
    </html>
  );
}`;
}

function generateHomePage(config: AppConfig): string {
  return `export default function Home() {
  const authEnabled = ${JSON.stringify(Boolean(config.app.auth?.enabled))};
  return (
    <div className="space-y-6">
      <section className="rounded-3xl border border-white/10 bg-white/5 p-6 shadow-soft backdrop-blur-xl md:p-8">
        <p className="text-[10px] font-semibold uppercase tracking-[0.35em] text-indigo-300/70">Overview</p>
        <div className="mt-3 flex flex-col gap-4 md:flex-row md:items-end md:justify-between">
          <div className="max-w-2xl">
            <h1 className="text-3xl font-bold tracking-tight text-white md:text-5xl">${config.app.name}</h1>
            <p className="mt-4 text-sm leading-7 text-slate-300 md:text-base">${config.app.description || 'Welcome to your generated app.'}</p>
          </div>
          <div className="grid grid-cols-2 gap-3 text-sm md:min-w-80">
            <div className="rounded-2xl border border-white/10 bg-slate-950/60 p-4">
              <div className="text-slate-400">Responsive</div>
              <div className="mt-1 font-semibold text-white">Mobile first</div>
            </div>
            <div className="rounded-2xl border border-white/10 bg-slate-950/60 p-4">
              <div className="text-slate-400">Installable</div>
              <div className="mt-1 font-semibold text-white">PWA ready</div>
            </div>
          </div>
        </div>
      </section>
      {authEnabled && (
        <section className="rounded-3xl border border-white/10 bg-slate-950/60 p-5 shadow-soft md:p-6">
          <p className="text-[10px] font-semibold uppercase tracking-[0.35em] text-indigo-300/70">Authentication</p>
          <h2 className="mt-2 text-xl font-semibold text-white">Secure sign-in is enabled for this app</h2>
          <p className="mt-2 max-w-2xl text-sm leading-7 text-slate-300">Use the generated auth page to sign in, create accounts, and switch OAuth providers based on the app configuration.</p>
          <div className="mt-5">
            <a href="/auth" className="inline-flex items-center gap-2 rounded-full bg-indigo-500 px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-indigo-400">
              Open auth screen
              <ArrowRight className="h-4 w-4" />
            </a>
          </div>
        </section>
      )}
      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        <div className="rounded-2xl border border-white/10 bg-slate-950/60 p-5">
          <p className="text-sm text-slate-400">Fast setup</p>
          <p className="mt-2 text-lg font-semibold text-white">Generate, deploy, install</p>
        </div>
        <div className="rounded-2xl border border-white/10 bg-slate-950/60 p-5">
          <p className="text-sm text-slate-400">Responsive layout</p>
          <p className="mt-2 text-lg font-semibold text-white">Sidebar on desktop, bottom nav on mobile</p>
        </div>
        <div className="rounded-2xl border border-white/10 bg-slate-950/60 p-5">
          <p className="text-sm text-slate-400">Offline ready</p>
          <p className="mt-2 text-lg font-semibold text-white">Manifest + service worker</p>
        </div>
        <div className="rounded-2xl border border-white/10 bg-slate-950/60 p-5">
          <p className="text-sm text-slate-400">Data driven</p>
          <p className="mt-2 text-lg font-semibold text-white">Entity pages scale to your config</p>
        </div>
      </div>
    </div>
  );
}`;
}

function generateAuthProvidersRoute(config: AppConfig): string {
  return `import { NextResponse } from "next/server";

function isUnsetOrPlaceholder(value: string | undefined) {
  if (!value) return true;
  const normalized = value.trim().toLowerCase();
  if (!normalized) return true;
  return normalized.includes("placeholder") || normalized.includes("your-google") || normalized.includes("your-github") || normalized.includes("replace");
}

export async function GET() {
  const enabled = ${JSON.stringify(Boolean(config.app.auth?.enabled))};
  const configProviders = ${JSON.stringify(config.app.auth?.providers || {})};
  const googleConfigured = !isUnsetOrPlaceholder(process.env.GOOGLE_CLIENT_ID) && !isUnsetOrPlaceholder(process.env.GOOGLE_CLIENT_SECRET);
  const githubConfigured = !isUnsetOrPlaceholder(process.env.GITHUB_CLIENT_ID) && !isUnsetOrPlaceholder(process.env.GITHUB_CLIENT_SECRET);

  return NextResponse.json({
    success: true,
    data: {
      enabled,
      google: enabled && configProviders.google !== false && googleConfigured,
      github: enabled && configProviders.github !== false && githubConfigured,
    },
  });
}`;
}

function generateAuthPage(config: AppConfig): string {
  const authEnabled = Boolean(config.app.auth?.enabled);
  const providers = config.app.auth?.providers || {};

  return `"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { AlertCircle, ArrowRight, Loader2, ShieldCheck } from "lucide-react";

type ProviderState = {
  enabled: boolean;
  google: boolean;
  github: boolean;
};

function GoogleLogo({ className = "h-4 w-4" }: { className?: string }) {
  return (
    <svg viewBox="0 0 24 24" className={className} aria-hidden="true">
      <path fill="#EA4335" d="M12 10.2v3.9h5.4c-.2 1.2-.9 2.2-1.9 2.9l3 2.3c1.8-1.6 2.8-3.9 2.8-6.7 0-.7-.1-1.4-.2-2H12z" />
      <path fill="#34A853" d="M12 22c2.6 0 4.8-.9 6.4-2.4l-3-2.3c-.8.6-2 .9-3.4.9-2.6 0-4.8-1.8-5.6-4.2H3.3v2.6C4.9 19.8 8.2 22 12 22z" />
      <path fill="#4A90E2" d="M6.4 14c-.2-.6-.3-1.3-.3-2s.1-1.4.3-2V7.4H3.3A10 10 0 002 12c0 1.7.4 3.4 1.3 4.6L6.4 14z" />
      <path fill="#FBBC05" d="M12 5.8c1.5 0 2.8.5 3.8 1.5l2.8-2.8C16.8 2.8 14.6 2 12 2 8.2 2 4.9 4.2 3.3 7.4L6.4 10c.8-2.4 3-4.2 5.6-4.2z" />
    </svg>
  );
}

function GitHubLogo({ className = "h-4 w-4" }: { className?: string }) {
  return (
    <svg viewBox="0 0 24 24" className={className} aria-hidden="true">
      <path
        fill="currentColor"
        d="M12 .5C5.6.5.5 5.7.5 12.1c0 5.1 3.3 9.5 7.9 11.1.6.1.8-.2.8-.6v-2.2c-3.2.7-3.9-1.4-3.9-1.4-.5-1.4-1.3-1.7-1.3-1.7-1.1-.7.1-.7.1-.7 1.2.1 1.9 1.3 1.9 1.3 1.1 1.9 2.9 1.3 3.6 1 .1-.8.4-1.3.8-1.6-2.5-.3-5.2-1.3-5.2-5.8 0-1.3.5-2.4 1.2-3.3-.1-.3-.5-1.6.1-3.2 0 0 1-.3 3.3 1.2a11.5 11.5 0 016 0c2.3-1.5 3.3-1.2 3.3-1.2.6 1.6.2 2.9.1 3.2.8.9 1.2 2 1.2 3.3 0 4.6-2.7 5.5-5.2 5.8.4.3.8 1 .8 2v3c0 .4.2.7.8.6a11.6 11.6 0 007.9-11.1C23.5 5.7 18.4.5 12 .5z"
      />
    </svg>
  );
}

const AUTH_ENABLED = ${JSON.stringify(authEnabled)};
const CONFIG_PROVIDERS = ${JSON.stringify(providers)};

export default function AuthPage() {
  const [mode, setMode] = useState<"login" | "register">("login");
  const [providers, setProviders] = useState<ProviderState | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let mounted = true;
    fetch("/api/auth/providers")
      .then((res) => res.json())
      .then((json) => {
        if (!mounted) return;
        if (json?.success) {
          setProviders(json.data as ProviderState);
        }
      })
      .catch(() => {
        if (mounted) setProviders({ enabled: AUTH_ENABLED, google: false, github: false });
      })
      .finally(() => {
        if (mounted) setLoading(false);
      });

    return () => {
      mounted = false;
    };
  }, []);

  const providerState = useMemo(() => {
    const base = providers || { enabled: AUTH_ENABLED, google: false, github: false };
    return {
      enabled: base.enabled && AUTH_ENABLED,
      google: base.google && CONFIG_PROVIDERS.google !== false,
      github: base.github && CONFIG_PROVIDERS.github !== false,
    };
  }, [providers]);

  if (!AUTH_ENABLED) {
    return (
      <main className="min-h-screen bg-slate-950 px-6 py-16 text-white">
        <div className="mx-auto flex w-full max-w-3xl flex-col items-center rounded-[2rem] border border-white/10 bg-white/5 p-8 text-center shadow-2xl shadow-black/30 backdrop-blur-xl">
          <ShieldCheck className="h-12 w-12 text-emerald-400" />
          <h1 className="mt-4 text-3xl font-bold">Authentication is disabled</h1>
          <p className="mt-3 max-w-xl text-sm leading-7 text-slate-300">This app was generated with auth turned off in the config, so users can go straight to the application experience.</p>
          <Link href="/" className="mt-8 inline-flex items-center gap-2 rounded-full bg-indigo-500 px-5 py-3 text-sm font-semibold text-white transition hover:bg-indigo-400">
            Continue to app
            <ArrowRight className="h-4 w-4" />
          </Link>
        </div>
      </main>
    );
  }

  const showRegister = mode === "register";

  return (
    <main className="min-h-screen bg-[radial-gradient(circle_at_top,_rgba(99,102,241,0.22),_transparent_35%),linear-gradient(180deg,#020617_0%,#030712_100%)] px-4 py-6 text-white sm:px-6 lg:px-8">
      <div className="mx-auto grid min-h-[calc(100vh-3rem)] w-full max-w-6xl items-center gap-8 lg:grid-cols-[1.1fr_0.9fr]">
        <section className="relative overflow-hidden rounded-[2rem] border border-white/10 bg-white/5 p-8 shadow-2xl shadow-black/30 backdrop-blur-xl lg:p-10">
          <div className="absolute inset-0 bg-[radial-gradient(circle_at_top_right,_rgba(56,189,248,0.18),_transparent_28%),radial-gradient(circle_at_bottom_left,_rgba(168,85,247,0.2),_transparent_32%)]" />
          <div className="relative">
            <h1 className="mt-6 max-w-xl text-4xl font-black tracking-tight sm:text-5xl">${config.app.name}</h1>
            <p className="mt-4 max-w-2xl text-sm leading-7 text-slate-300 sm:text-base">${config.app.description || "Welcome to your generated app."}</p>
          </div>
        </section>

        <section className="rounded-[2rem] border border-white/10 bg-slate-950/80 p-6 shadow-2xl shadow-black/30 backdrop-blur-xl sm:p-8">
          <div className="flex items-center justify-between gap-3">
            <h2 className="text-2xl font-bold">{showRegister ? "Create your account" : "Sign in to continue"}</h2>
          </div>

          <div className="mt-6 flex rounded-2xl border border-white/10 bg-white/5 p-1">
            <button onClick={() => setMode("login")} className={"flex-1 rounded-xl px-4 py-3 text-sm font-semibold transition " + (mode === "login" ? "bg-white text-black" : "text-white/60 hover:text-white")}>Login</button>
            <button onClick={() => setMode("register")} className={"flex-1 rounded-xl px-4 py-3 text-sm font-semibold transition " + (mode === "register" ? "bg-white text-black" : "text-white/60 hover:text-white")}>Register</button>
          </div>

          <div className="mt-6 space-y-4">
            <label className="block">
              <span className="mb-2 block text-xs font-semibold uppercase tracking-[0.2em] text-slate-400">Email</span>
              <input className="w-full rounded-2xl border border-white/10 bg-slate-950/70 px-4 py-3 text-sm text-white outline-none ring-0 placeholder:text-slate-500 focus:border-indigo-400" placeholder="you@example.com" />
            </label>
            <label className="block">
              <span className="mb-2 block text-xs font-semibold uppercase tracking-[0.2em] text-slate-400">Password</span>
              <input type="password" className="w-full rounded-2xl border border-white/10 bg-slate-950/70 px-4 py-3 text-sm text-white outline-none ring-0 placeholder:text-slate-500 focus:border-indigo-400" placeholder="••••••••" />
            </label>

            {showRegister && (
              <label className="block">
                <span className="mb-2 block text-xs font-semibold uppercase tracking-[0.2em] text-slate-400">Name</span>
                <input className="w-full rounded-2xl border border-white/10 bg-slate-950/70 px-4 py-3 text-sm text-white outline-none ring-0 placeholder:text-slate-500 focus:border-indigo-400" placeholder="Your name" />
              </label>
            )}

            <button className="inline-flex w-full items-center justify-center gap-2 rounded-2xl bg-indigo-500 px-5 py-3.5 text-sm font-semibold text-white transition hover:bg-indigo-400">
              {showRegister ? "Create account" : "Sign in"}
              <ArrowRight className="h-4 w-4" />
            </button>
          </div>

          {providerState.google || providerState.github ? (
            <div className="mt-8">
              <div className="flex items-center gap-3">
                <div className="h-px flex-1 bg-white/10" />
                <span className="text-[10px] font-semibold uppercase tracking-[0.3em] text-slate-500">Or continue with</span>
                <div className="h-px flex-1 bg-white/10" />
              </div>

              <div className="mt-4 grid gap-3">
                {providerState.google && (
                  <button className="inline-flex items-center justify-center gap-2 rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-sm font-semibold text-white transition hover:bg-white/10">
                    {loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <GoogleLogo className="h-4 w-4" />}
                    Continue with Google
                  </button>
                )}
                {providerState.github && (
                  <button className="inline-flex items-center justify-center gap-2 rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-sm font-semibold text-white transition hover:bg-white/10">
                    <GitHubLogo className="h-4 w-4" />
                    Continue with GitHub
                  </button>
                )}
              </div>
            </div>
          ) : (
            <div className="mt-8 rounded-2xl border border-amber-500/20 bg-amber-500/10 p-4 text-sm text-amber-200">
              <div className="flex items-start gap-2">
                <AlertCircle className="mt-0.5 h-4 w-4 shrink-0" />
                <p>OAuth buttons are hidden until the app config and environment both enable a provider.</p>
              </div>
            </div>
          )}
        </section>
      </div>
    </main>
  );
}`;
}

function generateApiRoute(entityName: string, entityConfig: EntityConfig): string {
  const modelName = entityName.charAt(0).toUpperCase() + entityName.slice(1);
  return `import { NextResponse } from "next/server";
import prisma from "@/lib/prisma";

export async function GET(request: Request) {
  try {
    const records = await prisma.${modelName.toLowerCase()}.findMany({
      orderBy: { createdAt: "desc" }
    });
    return NextResponse.json({ success: true, data: records });
  } catch (error) {
    return NextResponse.json({ success: false, error: "Failed to fetch data" }, { status: 500 });
  }
}

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const record = await prisma.${modelName.toLowerCase()}.create({
      data: body
    });
    return NextResponse.json({ success: true, data: record }, { status: 201 });
  } catch (error) {
    return NextResponse.json({ success: false, error: "Failed to create record" }, { status: 500 });
  }
}`;
}

function generateApiIdRoute(entityName: string): string {
  const modelName = entityName.charAt(0).toUpperCase() + entityName.slice(1);
  return `import { NextResponse } from "next/server";
import prisma from "@/lib/prisma";

export async function GET(request: Request, { params }: { params: { id: string } }) {
  try {
    const record = await prisma.${modelName.toLowerCase()}.findUnique({
      where: { id: params.id }
    });
    if (!record) return NextResponse.json({ success: false, error: "Not found" }, { status: 404 });
    return NextResponse.json({ success: true, data: record });
  } catch (error) {
    return NextResponse.json({ success: false, error: "Failed to fetch record" }, { status: 500 });
  }
}

export async function PUT(request: Request, { params }: { params: { id: string } }) {
  try {
    const body = await request.json();
    const record = await prisma.${modelName.toLowerCase()}.update({
      where: { id: params.id },
      data: body
    });
    return NextResponse.json({ success: true, data: record });
  } catch (error) {
    return NextResponse.json({ success: false, error: "Failed to update record" }, { status: 500 });
  }
}

export async function DELETE(request: Request, { params }: { params: { id: string } }) {
  try {
    await prisma.${modelName.toLowerCase()}.delete({
      where: { id: params.id }
    });
    return NextResponse.json({ success: true, data: { message: "Deleted" } });
  } catch (error) {
    return NextResponse.json({ success: false, error: "Failed to delete record" }, { status: 500 });
  }
}`;
}

function generateEntityPage(pageName: string, entityName: string): string {
  return `"use client";
import { useEffect, useMemo, useState } from "react";
import { Search, Plus, MoreHorizontal } from "lucide-react";

export default function Page() {
  const [data, setData] = useState([]);
  const [loading, setLoading] = useState(true);
  const [query, setQuery] = useState("");

  useEffect(() => {
    fetch("/api/${entityName}")
      .then(res => res.json())
      .then(json => {
        if (json.success) setData(json.data);
        setLoading(false);
      });
  }, []);

  const filteredData = useMemo(() => {
    if (!query) return data;
    const search = query.toLowerCase();
    return data.filter((row: any) =>
      Object.values(row).some((value) => String(value).toLowerCase().includes(search))
    );
  }, [data, query]);

  return (
    <div className="space-y-6">
      <section className="rounded-3xl border border-white/10 bg-white/5 p-5 shadow-soft backdrop-blur-xl md:p-6">
        <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
          <div>
            <p className="text-[10px] font-semibold uppercase tracking-[0.35em] text-indigo-300/70">${pageName}</p>
            <h1 className="mt-2 text-2xl font-bold text-white md:text-4xl">${pageName}</h1>
          </div>
          <div className="flex flex-col gap-3 sm:flex-row">
            <label className="flex min-w-0 items-center gap-2 rounded-2xl border border-white/10 bg-slate-950/60 px-4 py-3 text-sm text-slate-300">
              <Search className="h-4 w-4 text-slate-400" />
              <input
                value={query}
                onChange={(e) => setQuery(e.target.value)}
                placeholder="Search records"
                className="w-full bg-transparent outline-none placeholder:text-slate-500"
              />
            </label>
            <button className="inline-flex items-center justify-center gap-2 rounded-2xl bg-indigo-500 px-4 py-3 text-sm font-semibold text-white shadow-lg shadow-indigo-500/20 transition hover:bg-indigo-400 active:scale-[0.98]">
              <Plus className="h-4 w-4" />
              Add
            </button>
          </div>
        </div>
      </section>

      <div className="rounded-3xl border border-white/10 bg-slate-950/60 shadow-soft overflow-hidden">
        {loading ? (
          <div className="p-8 text-center text-slate-400">Loading data...</div>
        ) : filteredData.length === 0 ? (
          <div className="p-8 text-center text-slate-400">No records found.</div>
        ) : (
          <>
            <div className="hidden overflow-x-auto md:block">
              <table className="w-full border-collapse text-left">
                <thead>
                  <tr className="border-b border-white/10 bg-white/[0.03]">
                    {Object.keys(filteredData[0]).filter(k => k !== 'id').map(key => (
                      <th key={key} className="p-4 text-xs font-semibold uppercase tracking-[0.2em] text-slate-400">{key}</th>
                    ))}
                    <th className="p-4 text-xs font-semibold uppercase tracking-[0.2em] text-slate-400"><MoreHorizontal className="h-4 w-4" /></th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-white/5">
                  {filteredData.map((row: any) => (
                    <tr key={row.id} className="transition hover:bg-white/[0.03]">
                      {Object.keys(row).filter(k => k !== 'id').map(key => (
                        <td key={key} className="p-4 text-sm text-slate-300">{String(row[key])}</td>
                      ))}
                      <td className="p-4 text-slate-500">
                        <MoreHorizontal className="h-4 w-4" />
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            <div className="grid gap-3 p-3 md:hidden">
              {filteredData.map((row: any) => (
                <article key={row.id} className="rounded-2xl border border-white/10 bg-slate-950/70 p-4">
                  {Object.keys(row).filter(k => k !== 'id').map(key => (
                    <div key={key} className="mb-3 last:mb-0">
                      <div className="text-[10px] font-semibold uppercase tracking-[0.2em] text-slate-500">{key}</div>
                      <div className="mt-1 break-words text-sm text-slate-200">{String(row[key])}</div>
                    </div>
                  ))}
                </article>
              ))}
            </div>
          </>
        )}
      </div>
    </div>
  );
}`;
}

function generateDashboardPage(page: Extract<AppConfig["pages"][number], { type: "dashboard" }>): string {
  const widgets = JSON.stringify(page.widgets, null, 2);

  return `"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { Loader2 } from "lucide-react";

const widgets = ${widgets};

export default function Page() {
  const [widgetState, setWidgetState] = useState<Record<string, { loading: boolean; value?: number; groups?: Array<{ key: string; value: number }>; records?: Array<{ id: string; data: Record<string, unknown>; createdAt: string }> }>>({});
  const params = useParams();
  const appId = params.appId as string;

  useEffect(() => {
    let cancelled = false;

    async function loadWidgets() {
      const entries = await Promise.all(widgets.map(async (widget: any) => {
        try {
          if (widget.type === "stat") {
            const searchParams = new URLSearchParams({ operation: widget.operation || "count" });
            if (widget.field) searchParams.set("field", widget.field);
            const response = await fetch("/api/entities/" + appId + "/${'${'}widget.entity}/stats?" + searchParams.toString());
            const json = await response.json();
            return [widget.label, { loading: false, value: json?.data?.value ?? 0, groups: json?.data?.groups }];
          }

          if (widget.type === "list") {
            const response = await fetch("/api/entities/" + appId + "/${'${'}widget.entity}/recent?limit=" + (${''}widget.limit || 5));
            const json = await response.json();
            return [widget.label, { loading: false, records: json?.data ?? [] }];
          }

          if (widget.type === "chart") {
            const searchParams = new URLSearchParams({ operation: widget.operation || "count" });
            if (widget.field) searchParams.set("field", widget.field);
            if (widget.groupBy) searchParams.set("groupBy", widget.groupBy);
            const response = await fetch("/api/entities/" + appId + "/${'${'}widget.entity}/stats?" + searchParams.toString());
            const json = await response.json();
            return [widget.label, { loading: false, value: json?.data?.value ?? 0, groups: json?.data?.groups }];
          }

          return [widget.label, { loading: false }];
        } catch {
          return [widget.label, { loading: false, value: 0, records: [], groups: [] }];
        }
      }));

      if (!cancelled) {
        setWidgetState(Object.fromEntries(entries));
      }
    }

    loadWidgets();
    return () => {
      cancelled = true;
    };
  }, [appId]);

  return (
    <div className="space-y-6">
      <section className="rounded-3xl border border-white/10 bg-white/5 p-6 shadow-soft backdrop-blur-xl md:p-8">
        <p className="text-[10px] font-semibold uppercase tracking-[0.35em] text-indigo-300/70">${page.name}</p>
        <h1 className="mt-3 text-3xl font-bold tracking-tight text-white md:text-5xl">${page.name}</h1>
        <p className="mt-4 text-sm leading-7 text-slate-300 md:text-base">Dashboard generated from your JSON widget configuration.</p>
      </section>

      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
        ${page.widgets.map((widget) => {
          if (widget.type === "stat") {
            return `<div className=\"rounded-2xl border border-white/10 bg-slate-950/60 p-5\"><p className=\"text-sm text-slate-400\">${widget.label}</p><p className=\"mt-2 text-2xl font-bold text-white\">{widgetState[\"${widget.label}\"]?.loading ? <Loader2 className=\"h-5 w-5 animate-spin text-indigo-400\" /> : (widgetState[\"${widget.label}\"]?.value ?? 0).toLocaleString()}</p></div>`;
          }
          if (widget.type === "list") {
            return `<div className=\"rounded-2xl border border-white/10 bg-slate-950/60 p-5\"><p className=\"text-sm font-medium text-white/70\">${widget.label}</p><div className=\"mt-4 space-y-2\">{(widgetState[\"${widget.label}\"]?.records || []).map((record) => <div key={record.id} className=\"rounded-xl bg-white/5 px-3 py-2 text-sm text-slate-200\">{String(record.data[Object.keys(record.data)[0]] ?? \"Untitled\")}</div>)}</div></div>`;
          }
          return `<div className=\"rounded-2xl border border-white/10 bg-slate-950/60 p-5\"><p className=\"text-sm font-medium text-white/70\">${widget.label}</p><p className=\"mt-2 text-sm text-slate-400\">Chart widgets are driven by the same entity stats endpoint and can be expanded further as needed.</p></div>`;
        }).join("\n        ")}
      </div>
    </div>
  );
}`;
}

function generateDetailPage(page: Extract<AppConfig["pages"][number], { type: "detail" }>): string {
  const fields = page.fields && page.fields.length > 0 ? JSON.stringify(page.fields) : "null";

  return `"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";

export default function Page() {
  const params = useParams();
  const appId = params.appId as string;
  const recordId = params.id as string;
  const [record, setRecord] = useState<Record<string, unknown> | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch("/api/entities/" + appId + "/${page.entity}/" + recordId)
      .then((response) => response.json())
      .then((json) => {
        if (json.success) setRecord(json.data?.data ?? json.data);
        setLoading(false);
      })
      .catch(() => setLoading(false));
  }, [appId, recordId]);

  const visibleFields = ${fields} ?? Object.keys(record || {});

  return (
    <div className="space-y-6">
      <section className="rounded-3xl border border-white/10 bg-white/5 p-6 shadow-soft backdrop-blur-xl md:p-8">
        <p className="text-[10px] font-semibold uppercase tracking-[0.35em] text-indigo-300/70">${page.name}</p>
        <h1 className="mt-3 text-3xl font-bold tracking-tight text-white md:text-5xl">${page.name}</h1>
        <p className="mt-4 text-sm leading-7 text-slate-300 md:text-base">Record details generated from the JSON config.</p>
      </section>

      <div className="rounded-3xl border border-white/10 bg-slate-950/60 p-5 shadow-soft md:p-6">
        {loading ? (
          <div className="p-8 text-center text-slate-400">Loading record...</div>
        ) : !record ? (
          <div className="p-8 text-center text-slate-400">No record found.</div>
        ) : (
          <dl className="grid gap-4 md:grid-cols-2">
            {visibleFields.map((field: string) => (
              <div key={field} className="rounded-2xl border border-white/10 bg-black/20 p-4">
                <dt className="text-[10px] font-semibold uppercase tracking-[0.2em] text-slate-500">{field}</dt>
                <dd className="mt-2 break-words text-sm text-slate-200">{String(record[field] ?? "—")}</dd>
              </div>
            ))}
          </dl>
        )}
      </div>
    </div>
  );
}`;
}
